#!/bin/bash
# Script to help set up GitHub token for pushing

echo "============================================================"
echo "GitHub Token Setup Instructions"
echo "============================================================"
echo ""
echo "Since GitHub no longer accepts passwords for Git operations,"
echo "you need to use a Personal Access Token (PAT)."
echo ""
echo "To create a new token with proper permissions:"
echo ""
echo "1. Go to: https://github.com/settings/tokens/new"
echo ""
echo "2. Fill in the form:"
echo "   - Note: irt-erp-bench-token"
echo "   - Expiration: Choose your preference"
echo "   - Scopes: Check 'repo' (Full control of private repositories)"
echo ""
echo "3. Click 'Generate token'"
echo ""
echo "4. Copy the token (starts with github_pat_...)"
echo ""
echo "5. Update the token in push_to_github.sh:"
echo "   TOKEN=\"your_new_token_here\""
echo ""
echo "============================================================"
echo ""
echo "To use environment variable:"
echo "   export GITHUB_TOKEN='your_token_here'"
echo ""
echo "To update permissions on existing token:"
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Find your token or create a new one with 'repo' scope"
echo ""

